class Api::V1::HelloWorldController < ApplicationController
    def hello_world
      render json: {
      name:"Untitled",
      timePeriod:500,
      clockEnabled:true,
      projectId:"PNJWPFpvnR2wa0sHSQ7W",
      focussedCircuit:47885142395,
      orderedTabs:["47885142395"],
      scopes:[
        {
          layout:{width:100,height:60,title_x:50,title_y:13,titleEnabled:true},
          verilogMetadata:{isVerilogCircuit:false,isMainCircuit:false,code:"// Write Some Verilog Code Here!",subCircuitScopeIds:[]},
          allNodes:[
            {x:10,y:0,type:1,bitWidth:1,label:"",connections:[2]},
            {x:10,y:0,type:1,bitWidth:1,label:"",connections:[3]},
            {x:-10,y:-10,type:0,bitWidth:1,label:"",connections:[0]},
            {x:-10,y:10,type:0,bitWidth:1,label:"",connections:[1]},
            {x:20,y:0,type:1,bitWidth:1,label:"",connections:[]},
            {x:10,y:0,type:0,bitWidth:1,label:"",connections:[]}
          ],
          id:47885142395,
          name:"Main",
          Input:[
            {
              x:410,y:60,objectType:"Input",label:"",
              direction:"RIGHT",labelDirection:"LEFT",propagationDelay:0,
              customData:{
                nodes:{output1:0},
                values:{state:1},
                constructorParamaters:["RIGHT",1,{x:0,y:20,id:"eB342mAc6WpcQeRxAwEH"}]
              }
            },
            {
              x:410,y:80,objectType:"Input",label:"",direction:"RIGHT",labelDirection:"LEFT",
              propagationDelay:0,customData:{
                nodes:{output1:1},
                values:{state:1},
                constructorParamaters:["RIGHT",1,{x:0,y:40,id:"hqSnVMWErwiVrpYhvSKG"}]
              }
            }
          ],
          Output:[
            {
              x:580,y:70,objectType:"Output",label:"",direction:"LEFT",labelDirection:"RIGHT",
              propagationDelay:0,customData:{
                nodes:{inp1:5},
                constructorParamaters:["LEFT",1,{x:100,y:20,id:"mPRJCmLElX1f5Vto7YST"}]
              }
            }
          ],
          OrGate:[
            {
              x:490,y:70,objectType:"OrGate",label:"",direction:"RIGHT",labelDirection:"LEFT",
              propagationDelay:10,
              customData:{
                constructorParamaters:["RIGHT",2,1],
                nodes:{inp:[2,3],output1:4}
              }
            }
          ],
          restrictedCircuitElementsUsed:[],
          nodes:[]
        }
      ]
    }
    end
end

